### ISSUE TITLE
you need a readme file - the project won't compile stand alone. 

### ISSUE THREAD

**Issue by johndpope** [etoile/SourceCodeKit#6]
I reverted to this codebase as I could get up and running simpler. 
Please spell out steps to get this to compile.

**Comment by davidchisnall** [comment]
What errors do you get?  The last time I tried to compile it, gmake && gmake install was enough.

**Comment by johndpope** [comment]
I see you spelled it out here in INSTALL 

 ->     * EtoileFoundation, which can be found in Etoile/Frameworks/EtoileFoundation

I'm so used to cocoa pods / and git init recursive sub modules - 
Where to put these files so I can build from xcode project???

This other project builds fine. Very simple fork -> 
https://github.com/phausler/SourceCodeKit


I see the etoile has a bunch of depencies..... arrhh......

From GNUstep: gnustep-make, gnustep-base, gnustep-gui, gnustep-back

From Freedesktop: D-Bus, HAL, startup-notification, Xcursor

libpng, zlib, OniGuruma, XScreenSaver, LLVM, GMP, Lemon, SQLite, OSS, FFmpeg (libavcodec and libavformat), TagLib, MPEG4IP (libmp4v2), Graphviz, Discount

**Comment by davidchisnall** [comment]
I've never tried building on OS X.  If someone wants to provide an XCode project, then I'd be happy to use it.  The only dependencies should be Foundation/AppKit, EtoileFoundation, and libclang.  I believe that XCode ships with a libclang.dylib, though possibly not with the headers.

**Comment by johndpope** [comment]
Hi Dave,  the libclang.dylib is not the problem. It's the dependencies on EtoileFoundation and how to link them together. I'll give it a crack tomorrow as the other project doesn't have any unit tests and I can see there's been more work on this master branch.

**Comment by AlessandroSangiuliano** [comment]
I have SourceCodeKit on OS X, because I was porting CodeEditor on OS X. I done the port because I did need to complete some work on a SourceCodeKit branch and CodeEditor, but I had problems with some include files, but that was my fail. Then I did not find the right retail of time to complete the work. 

Actually I’m not at home until september, this means that is very difficult form me to provide the code or any help, indeed I just write to inform that the port is feasible without so many problems, especially if you have a good knowledge of OS X (not my case, I use it very few).

Alex.

> Il giorno 23/lug/2015, alle ore 10:57, John Pope <notifications@github.com> ha scritto:
> 
> Hi Dave, the libclang.dylib is not the problem. It's the dependencies on EtoileFoundation and how to link them together. I'll give it a crack tomorrow as the other project doesn't have any unit tests and I can see there's been more work on this master branch.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/etoile/SourceCodeKit/issues/6#issuecomment-124026376>.
> 


-----------------------------------------------------------------
A: "Hey dude, where are you from?"
B: “I’m from Uros”
A: “What?”
B: “Uros, the Uranos' world capital”
A: “Hey dude, you look so strange and white. You should eat some meat!”
B: “We don’t need to eat”
A: “Hey man, that dude looks so strange, He doesn’t need to eat”
C: “OMG! So strange, he also is so white!”
D: “Why do I have to hunt to eat and survive and he doesn’t need to eat to survive? I hate him!”
<…>

**Comment by johndpope** [comment]
Hi Alessandro,

I managed to cherry pick some of the updates around skintrospection into here 
https://github.com/phausler/SourceCodeKit
(haven't pushed code yet)
There were some array extensions - but I re-wrote the code so it didn't depend on them.
Thanks for reaching out.  

P.S. I'm attempting to build an objective-c to swift converter. there's some ruby code online swiftier.rb that I got some mileage today - have merged this code into another library which shows some promise.

**Comment by qmathe** [comment]
Hi John,

The easiest way to compile SourceCodeKit on OS X is to check out the entire Étoilé repository. 

First, check out https://github.com/etoile/Etoile, then inside it, there is a script etoile-fetch.sh. If you run, it is going to check the other repositories including SourceCodeKit.

You can now go to Etoile/Developer/SourceCodeKit directory and open the Xcode project.
The Xcode project will be able to find the dependencies in the correct locations. 

To get libclang linked, Xcode.app must be inside /Applications. If it's not the case, create a symbolic link, or tweak the build settings and replace occurrences of '$(SYSTEM_APPS_DIR)/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib' with the correct Xcode path.

I just tested building SourceCodeKit on Yosemite with XCode 6.3.2, it works for me. For the test suite, there is a linker issue. I'll fix it in the coming days.

I'll update the INSTALL file to be clearer on how to use the Xcode project.

**Comment by johndpope** [comment]
great thx
